/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZaNasRouteImport } from './routes/za-nas'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PolitikaZaPoveritelnostRouteImport } from './routes/politika-za-poveritelnost'
import { Route as ObshtiUsloviyaRouteImport } from './routes/obshti-usloviya'
import { Route as MetaProductsDotcsvRouteImport } from './routes/meta-products[.]csv'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as KalkulatorRouteImport } from './routes/kalkulator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduktiIndexRouteImport } from './routes/produkti.index'
import { Route as ProduktiSlugRouteImport } from './routes/produkti.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const ZaNasRoute = ZaNasRouteImport.update({
  id: '/za-nas',
  path: '/za-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaZaPoveritelnostRoute = PolitikaZaPoveritelnostRouteImport.update({
  id: '/politika-za-poveritelnost',
  path: '/politika-za-poveritelnost',
  getParentRoute: () => rootRouteImport,
} as any)
const ObshtiUsloviyaRoute = ObshtiUsloviyaRouteImport.update({
  id: '/obshti-usloviya',
  path: '/obshti-usloviya',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaProductsDotcsvRoute = MetaProductsDotcsvRouteImport.update({
  id: '/meta-products.csv',
  path: '/meta-products.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorRoute = KalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktiIndexRoute = ProduktiIndexRouteImport.update({
  id: '/produkti/',
  path: '/produkti/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktiSlugRoute = ProduktiSlugRouteImport.update({
  id: '/produkti/$slug',
  path: '/produkti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kontakti': typeof KontaktiRoute
  '/meta-products.csv': typeof MetaProductsDotcsvRoute
  '/obshti-usloviya': typeof ObshtiUsloviyaRoute
  '/politika-za-poveritelnost': typeof PolitikaZaPoveritelnostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
  '/produkti/$slug': typeof ProduktiSlugRoute
  '/produkti/': typeof ProduktiIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kontakti': typeof KontaktiRoute
  '/meta-products.csv': typeof MetaProductsDotcsvRoute
  '/obshti-usloviya': typeof ObshtiUsloviyaRoute
  '/politika-za-poveritelnost': typeof PolitikaZaPoveritelnostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
  '/produkti/$slug': typeof ProduktiSlugRoute
  '/produkti': typeof ProduktiIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kontakti': typeof KontaktiRoute
  '/meta-products.csv': typeof MetaProductsDotcsvRoute
  '/obshti-usloviya': typeof ObshtiUsloviyaRoute
  '/politika-za-poveritelnost': typeof PolitikaZaPoveritelnostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
  '/produkti/$slug': typeof ProduktiSlugRoute
  '/produkti/': typeof ProduktiIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kalkulator'
    | '/kontakti'
    | '/meta-products.csv'
    | '/obshti-usloviya'
    | '/politika-za-poveritelnost'
    | '/sitemap.xml'
    | '/uslugi'
    | '/za-nas'
    | '/produkti/$slug'
    | '/produkti/'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kalkulator'
    | '/kontakti'
    | '/meta-products.csv'
    | '/obshti-usloviya'
    | '/politika-za-poveritelnost'
    | '/sitemap.xml'
    | '/uslugi'
    | '/za-nas'
    | '/produkti/$slug'
    | '/produkti'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kalkulator'
    | '/kontakti'
    | '/meta-products.csv'
    | '/obshti-usloviya'
    | '/politika-za-poveritelnost'
    | '/sitemap.xml'
    | '/uslugi'
    | '/za-nas'
    | '/produkti/$slug'
    | '/produkti/'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KalkulatorRoute: typeof KalkulatorRoute
  KontaktiRoute: typeof KontaktiRoute
  MetaProductsDotcsvRoute: typeof MetaProductsDotcsvRoute
  ObshtiUsloviyaRoute: typeof ObshtiUsloviyaRoute
  PolitikaZaPoveritelnostRoute: typeof PolitikaZaPoveritelnostRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UslugiRoute: typeof UslugiRoute
  ZaNasRoute: typeof ZaNasRoute
  ProduktiSlugRoute: typeof ProduktiSlugRoute
  ProduktiIndexRoute: typeof ProduktiIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/za-nas': {
      id: '/za-nas'
      path: '/za-nas'
      fullPath: '/za-nas'
      preLoaderRoute: typeof ZaNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-za-poveritelnost': {
      id: '/politika-za-poveritelnost'
      path: '/politika-za-poveritelnost'
      fullPath: '/politika-za-poveritelnost'
      preLoaderRoute: typeof PolitikaZaPoveritelnostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obshti-usloviya': {
      id: '/obshti-usloviya'
      path: '/obshti-usloviya'
      fullPath: '/obshti-usloviya'
      preLoaderRoute: typeof ObshtiUsloviyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-products.csv': {
      id: '/meta-products.csv'
      path: '/meta-products.csv'
      fullPath: '/meta-products.csv'
      preLoaderRoute: typeof MetaProductsDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator': {
      id: '/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof KalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkti/': {
      id: '/produkti/'
      path: '/produkti'
      fullPath: '/produkti/'
      preLoaderRoute: typeof ProduktiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkti/$slug': {
      id: '/produkti/$slug'
      path: '/produkti/$slug'
      fullPath: '/produkti/$slug'
      preLoaderRoute: typeof ProduktiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KalkulatorRoute: KalkulatorRoute,
  KontaktiRoute: KontaktiRoute,
  MetaProductsDotcsvRoute: MetaProductsDotcsvRoute,
  ObshtiUsloviyaRoute: ObshtiUsloviyaRoute,
  PolitikaZaPoveritelnostRoute: PolitikaZaPoveritelnostRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UslugiRoute: UslugiRoute,
  ZaNasRoute: ZaNasRoute,
  ProduktiSlugRoute: ProduktiSlugRoute,
  ProduktiIndexRoute: ProduktiIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
